package cli

import (
	"os"
	"path/filepath"
	"strings"
)

func generateClaudeCode(root string, artifacts packArtifacts, opts generatorOptions) (generatorSummary, error) {
	return generateClaudeCodeAt(scopeProject, root, artifacts, opts)
}

func generateClaudeCodeAt(scope installScope, root string, artifacts packArtifacts, opts generatorOptions) (generatorSummary, error) {
	content, err := buildIDEAgentsDoc(scope, root, artifacts, "claude-code", "CLAUDE.md")
	if err != nil {
		return generatorSummary{}, err
	}
	summary := generatorSummary{}
	relPath := "CLAUDE.md"
	if scope == scopeGlobal {
		relPath = ".claude/CLAUDE.md"
	}
	if err := writeGeneratedFile(root, relPath, []byte(content), opts, &summary); err != nil {
		return summary, err
	}
	return summary, nil
}

func generateOpenCode(root string, artifacts packArtifacts, opts generatorOptions) (generatorSummary, error) {
	return generateOpenCodeAt(scopeProject, root, artifacts, opts)
}

func generateOpenCodeAt(scope installScope, root string, artifacts packArtifacts, opts generatorOptions) (generatorSummary, error) {
	content, err := buildIDEAgentsDoc(scope, root, artifacts, "opencode", "OpenCode AGENTS.md")
	if err != nil {
		return generatorSummary{}, err
	}
	summary := generatorSummary{}
	relPath := ".opencode/AGENTS.md"
	if scope == scopeGlobal {
		relPath = ".config/opencode/AGENTS.md"
	}
	if err := writeGeneratedFile(root, relPath, []byte(content), opts, &summary); err != nil {
		return summary, err
	}
	return summary, nil
}

func buildIDEAgentsDoc(scope installScope, root string, artifacts packArtifacts, target, title string) (string, error) {
	agentsBody, err := readProjectFile(root, "AGENTS.md", "project/AGENTS.md")
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("<!-- ")
	b.WriteString(generatedMarker)
	b.WriteString(":")
	b.WriteString(target)
	b.WriteString(" -->\n\n")
	b.WriteString("# ")
	b.WriteString(title)
	b.WriteString("\n\n")
	b.WriteString("Generated by geremmyas from `AGENTS.md`, synced skills, and agents.\n")
	if scope == scopeGlobal {
		b.WriteString("Re-run `geremmyas global --targets ")
		b.WriteString(target)
		b.WriteString("` to refresh. Use `--force` to overwrite customized files.\n\n")
	} else {
		b.WriteString("Re-run `geremmyas sync` to refresh. Customize `AGENTS.md` or use `--force` to overwrite.\n\n")
	}
	b.WriteString("---\n\n")
	b.WriteString(strings.TrimSpace(agentsBody))
	b.WriteString("\n\n")

	if len(artifacts.skills) > 0 {
		b.WriteString("## Skills (on demand)\n\n")
		if scope == scopeGlobal {
			b.WriteString("Read the full procedure in `~/.agents/skills/<name>/SKILL.md` when the task matches:\n\n")
		} else {
			b.WriteString("Read the full procedure in `.github/skills/<name>/SKILL.md` when the task matches:\n\n")
		}
		for _, source := range artifacts.skills {
			skillMD, err := findSkillMarkdown(source)
			if err != nil {
				continue
			}
			content, err := readEmbeddedSource(skillMD)
			if err != nil {
				continue
			}
			fm, _, _ := parseMarkdownFrontmatter(content)
			name := fm.get("name")
			if name == "" {
				name = filepath.Base(filepath.Dir(skillMD))
			}
			desc := fm.get("description")
			if desc == "" {
				desc = name
			}
			b.WriteString("- **")
			b.WriteString(name)
			b.WriteString("**: ")
			b.WriteString(desc)
			if scope == scopeGlobal {
				b.WriteString(" → `")
				b.WriteString(globalSkillPath(name))
				b.WriteString("`")
			}
			b.WriteString("\n")
		}
		b.WriteByte('\n')
	}

	if len(artifacts.agents) > 0 {
		b.WriteString("## Agent roles\n\n")
		if scope == scopeGlobal {
			b.WriteString("No native @agent picker. With the `cursor` global target, roles live in `~/.cursor/rules/agent-*.mdc`.\n\n")
		} else {
			b.WriteString("No native @agent picker in this IDE. Read `.github/agents/<file>` when the user names the role:\n\n")
		}
		for _, source := range artifacts.agents {
			content, err := readEmbeddedSource(source)
			if err != nil {
				continue
			}
			fm, _, _ := parseMarkdownFrontmatter(content)
			name := strings.TrimSuffix(filepath.Base(source), ".agent.md")
			desc := fm.get("description")
			if desc == "" {
				desc = name
			}
			b.WriteString("- **")
			b.WriteString(name)
			b.WriteString("**: ")
			b.WriteString(desc)
			if scope != scopeGlobal {
				b.WriteString(" → `.github/agents/")
				b.WriteString(filepath.Base(source))
				b.WriteString("`")
			}
			b.WriteString("\n")
		}
		b.WriteByte('\n')
	}

	if artifacts.hasHooks {
		b.WriteString("## Guardrails\n\n")
		if scope == scopeGlobal {
			b.WriteString("Shell guardrails: Copilot project hooks in `.github/hooks/`; global Cursor hooks in `~/.cursor/hooks/` when `cursor` target is enabled.\n\n")
		} else {
			b.WriteString("Shell guardrails live in `.github/hooks/` (Copilot) and `.cursor/hooks/` (Cursor when `cursor` target enabled).\n\n")
		}
	}

	return b.String(), nil
}

func readProjectFile(root, relTarget, embedFallback string) (string, error) {
	path := filepath.Join(root, relTarget)
	if data, err := os.ReadFile(path); err == nil {
		return string(data), nil
	}
	return readEmbeddedSource(embedFallback)
}
