package cli

import (
	"os"
	"path/filepath"
	"strings"
)

func generateClaudeCodeAt(scope installScope, root string, artifacts packArtifacts, opts generatorOptions) (generatorSummary, error) {
	content, err := buildIDEAgentsDoc(scope, root, artifacts, "claude-code", "CLAUDE.md")
	if err != nil {
		return generatorSummary{}, err
	}
	summary := generatorSummary{}
	relPath := "CLAUDE.md"
	if scope == scopeGlobal {
		relPath = ".claude/CLAUDE.md"
	}
	if err := writeGeneratedFile(root, relPath, []byte(content), opts, &summary); err != nil {
		return summary, err
	}
	return summary, nil
}

func generateOpenCodeAt(scope installScope, root string, artifacts packArtifacts, opts generatorOptions) (generatorSummary, error) {
	content, err := buildIDEAgentsDoc(scope, root, artifacts, "opencode", "OpenCode AGENTS.md")
	if err != nil {
		return generatorSummary{}, err
	}
	summary := generatorSummary{}
	relPath := ".opencode/AGENTS.md"
	if scope == scopeGlobal {
		relPath = ".config/opencode/AGENTS.md"
	}
	if err := writeGeneratedFile(root, relPath, []byte(content), opts, &summary); err != nil {
		return summary, err
	}
	return summary, nil
}

func generateCodexAt(scope installScope, root string, artifacts packArtifacts, opts generatorOptions) (generatorSummary, error) {
	content, err := buildCodexAgentsDoc(scope, artifacts)
	if err != nil {
		return generatorSummary{}, err
	}
	summary := generatorSummary{}
	relPath := ".codex/AGENTS.md"
	if err := writeGeneratedFile(root, relPath, []byte(content), opts, &summary); err != nil {
		return summary, err
	}
	if scope == scopeGlobal {
		if err := mirrorCodexInstructions(root, artifacts); err != nil {
			return summary, err
		}
	}
	return summary, nil
}

func buildCodexAgentsDoc(scope installScope, artifacts packArtifacts) (string, error) {
	var b strings.Builder
	b.WriteString("<!-- ")
	b.WriteString(generatedMarker)
	b.WriteString(":codex -->\n\n# Codex AGENTS.md\n\n")
	if scope == scopeGlobal {
		b.WriteString("Follow the nearest project-local `AGENTS.md`; it overrides this global bootstrap.\n")
		b.WriteString("Codex discovers installed skills natively, so they are not duplicated here.\n\n")
	} else {
		b.WriteString("Follow `AGENTS.md` at the workspace root. This file only indexes Codex-specific on-demand resources.\n\n")
	}

	base, ok := instructionPointerBase(scope, TargetCodex)
	if !ok || len(artifacts.instructions) == 0 {
		return b.String(), nil
	}
	b.WriteString("## Instructions (on demand)\n\n")
	b.WriteString("Read the matching file only when edited paths match its glob:\n\n")
	for _, source := range artifacts.instructions {
		content, err := readEmbeddedSource(source)
		if err != nil {
			return "", err
		}
		fm, _, err := parseMarkdownFrontmatter(content)
		if err != nil {
			return "", err
		}
		b.WriteString("- `")
		b.WriteString(instructionApplyToLabel(fm.get("applyTo")))
		b.WriteString("` -> `")
		b.WriteString(base)
		b.WriteString("/")
		b.WriteString(filepath.Base(source))
		b.WriteString("`\n")
	}
	b.WriteByte('\n')
	return b.String(), nil
}

// mirrorCodexInstructions copies each pack instruction file into the Codex-owned
// ~/.codex/instructions/ directory so Codex can read them on demand. Codex has
// no applyTo instruction folder of its own, so the generated AGENTS.md indexes
// these files by their applyTo glob.
func mirrorCodexInstructions(root string, artifacts packArtifacts) error {
	if len(artifacts.instructions) == 0 {
		return nil
	}
	dir := filepath.Join(root, ".codex", "instructions")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	for _, source := range artifacts.instructions {
		content, err := readEmbeddedSource(source)
		if err != nil {
			return err
		}
		dest := filepath.Join(dir, filepath.Base(source))
		if err := os.WriteFile(dest, []byte(content), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func buildIDEAgentsDoc(scope installScope, root string, artifacts packArtifacts, target, title string) (string, error) {
	agentsBody, err := readProjectFile(root, "AGENTS.md", "project/AGENTS.md")
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("<!-- ")
	b.WriteString(generatedMarker)
	b.WriteString(":")
	b.WriteString(target)
	b.WriteString(" -->\n\n")
	b.WriteString("# ")
	b.WriteString(title)
	b.WriteString("\n\n")
	b.WriteString("Generated by geremmyas from `AGENTS.md`, synced skills, and agents.\n")
	if scope == scopeGlobal {
		b.WriteString("Re-run `geremmyas global --targets ")
		b.WriteString(target)
		b.WriteString("` to refresh. Use `--force` to overwrite customized files.\n\n")
	} else {
		b.WriteString("Re-run `geremmyas sync` to refresh. Customize `AGENTS.md` or use `--force` to overwrite.\n\n")
	}
	b.WriteString("---\n\n")
	b.WriteString(strings.TrimSpace(agentsBody))
	b.WriteString("\n\n")

	if base, ok := instructionPointerBase(scope, target); ok && len(artifacts.instructions) > 0 {
		b.WriteString("## Instructions (on demand)\n\n")
		b.WriteString("This assistant has no `applyTo` auto-loading. Read the matching file when you edit paths that match its glob:\n\n")
		for _, source := range artifacts.instructions {
			content, err := readEmbeddedSource(source)
			if err != nil {
				continue
			}
			fm, _, _ := parseMarkdownFrontmatter(content)
			file := filepath.Base(source)
			b.WriteString("- `")
			b.WriteString(instructionApplyToLabel(fm.get("applyTo")))
			b.WriteString("` → `")
			b.WriteString(base)
			b.WriteString("/")
			b.WriteString(file)
			b.WriteString("`\n")
		}
		b.WriteByte('\n')
	}

	if len(artifacts.skills) > 0 {
		b.WriteString("## Skills (on demand)\n\n")
		if scope == scopeGlobal {
			b.WriteString("Read the full procedure in `~/.agents/skills/<name>/SKILL.md` when the task matches:\n\n")
		} else {
			b.WriteString("Read the full procedure in `.github/skills/<name>/SKILL.md` when the task matches:\n\n")
		}
		for _, source := range artifacts.skills {
			skillMD, err := findSkillMarkdown(source)
			if err != nil {
				continue
			}
			content, err := readEmbeddedSource(skillMD)
			if err != nil {
				continue
			}
			fm, _, _ := parseMarkdownFrontmatter(content)
			name := fm.get("name")
			if name == "" {
				name = filepath.Base(filepath.Dir(skillMD))
			}
			desc := fm.get("description")
			if desc == "" {
				desc = name
			}
			b.WriteString("- **")
			b.WriteString(name)
			b.WriteString("**: ")
			b.WriteString(desc)
			if scope == scopeGlobal {
				b.WriteString(" → `")
				b.WriteString(globalSkillPath(name))
				b.WriteString("`")
			}
			b.WriteString("\n")
		}
		b.WriteByte('\n')
	}

	if len(artifacts.agents) > 0 {
		b.WriteString("## Agent roles\n\n")
		if scope == scopeGlobal {
			b.WriteString("No native @agent picker. With the `cursor` global target, roles live in `~/.cursor/rules/agent-*.mdc`.\n\n")
		} else {
			b.WriteString("No native @agent picker in this IDE. Read `.github/agents/<file>` when the user names the role:\n\n")
		}
		for _, source := range artifacts.agents {
			content, err := readEmbeddedSource(source)
			if err != nil {
				continue
			}
			fm, _, _ := parseMarkdownFrontmatter(content)
			name := strings.TrimSuffix(filepath.Base(source), ".agent.md")
			desc := fm.get("description")
			if desc == "" {
				desc = name
			}
			b.WriteString("- **")
			b.WriteString(name)
			b.WriteString("**: ")
			b.WriteString(desc)
			if scope != scopeGlobal {
				b.WriteString(" → `.github/agents/")
				b.WriteString(filepath.Base(source))
				b.WriteString("`")
			}
			b.WriteString("\n")
		}
		b.WriteByte('\n')
	}

	if artifacts.hasHooks {
		b.WriteString("## Guardrails\n\n")
		if scope == scopeGlobal {
			b.WriteString("Shell guardrails: Copilot project hooks in `.github/hooks/`; global Cursor hooks in `~/.cursor/hooks/` when `cursor` target is enabled.\n\n")
		} else {
			b.WriteString("Shell guardrails live in `.github/hooks/` (Copilot) and `.cursor/hooks/` (Cursor when `cursor` target enabled).\n\n")
		}
	}

	return b.String(), nil
}

func readProjectFile(root, relTarget, embedFallback string) (string, error) {
	path := filepath.Join(root, relTarget)
	if data, err := os.ReadFile(path); err == nil {
		return string(data), nil
	}
	return readEmbeddedSource(embedFallback)
}

// instructionPointerBase returns the base path the generated AGENTS.md should
// point to for on-demand instruction reads, and whether an Instructions section
// should be rendered at all. Project scope always points to the synced
// .github/instructions/ directory. Global scope only renders for Codex, which
// mirrors instructions into ~/.codex/instructions/; other global IDE targets
// have no mirror and are skipped.
func instructionPointerBase(scope installScope, target string) (string, bool) {
	if scope == scopeProject {
		return ".github/instructions", true
	}
	if target == "codex" {
		return "~/.codex/instructions", true
	}
	return "", false
}

// instructionApplyToLabel returns a human label for an instruction's applyTo
// glob, falling back to "all files" when the frontmatter omits it.
func instructionApplyToLabel(applyTo string) string {
	applyTo = strings.TrimSpace(applyTo)
	if applyTo == "" {
		return "all files"
	}
	return applyTo
}
