package dashboard

import (
	"fmt"
	"strings"
)

const readmeHeader = "<!-- geremmyas:generated — do not edit manually, regenerated by `geremmyas dashboard` -->\n\n# Specs Index (auto-generated by geremmyas dashboard)\n\n"

// GenerateReadme builds the compact specs/README.md index.
func GenerateReadme(data DashboardData) string {
	var b strings.Builder
	b.WriteString(readmeHeader)
	for _, fam := range data.Families {
		nums := specNumbersInFamily(fam)
		rangeLabel := ""
		if len(nums) > 0 {
			rangeLabel = fmt.Sprintf(" (%04d–%04d)", nums[0], nums[len(nums)-1])
		}
		b.WriteString("## ")
		b.WriteString(fam.Name)
		b.WriteString(rangeLabel)
		b.WriteByte('\n')
		b.WriteByte('\n')
		for _, ph := range fam.Phases {
			for _, spec := range ph.Specs {
				if spec.Deprecated {
					continue
				}
				b.WriteString(fmt.Sprintf("- %04d %s — %s\n", spec.Number, spec.Title, spec.Status))
			}
		}
		b.WriteByte('\n')
	}
	return b.String()
}

func specNumbersInFamily(fam Family) []int {
	var nums []int
	for _, ph := range fam.Phases {
		for _, s := range ph.Specs {
			nums = append(nums, s.Number)
		}
	}
	return nums
}
